name: Publish documentation

on:
  push:
    branches:
      - master
name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Doxygen
      run: sudo apt-get install doxygen graphviz
    - name: Generate Documentation
      run: doxygen Doxyfile
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        commit_message: "Publish documentation"

